import type { NextPage } from "next";
import type { ReactElement } from "react";
import Head from "next/head";
import ActivitySummary from "../components/ActivitySummary";
import CourseCommingSoon from "../components/CourseCommingSoon";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Jumbotron from "../components/Jumbotron";
import Layout from "../components/Layout";
import ListCourses from "../components/ListCourses";
import StudentFeedback from "../components/StudentFeedback";
import Subscribe from "../components/Subscribe";

const About = () => {
  return (
    <div className={"font-Inter text-sm"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      The online Master of Computer and Information Technology degree (MCIT
      Online) is an online masters degree in Computer Science tailored for
      non-Computer Science majors. Offered by the University of Pennsylvania,
      this new program brings the long-running, established on-campus MCIT
      degree online. The MCIT Online program empowers students without computer
      science backgrounds to succeed in computing and technology fields. MCIT
      Online students come from diverse academic backgrounds ranging from
      business and history to chemistry and medicine. The online Master of
      Computer and Information Technology degree (MCIT Online) is an online
      masters degree in Computer Science tailored for non-Computer Science
      majors. Offered by the University of Pennsylvania, this new program brings
      the long-running, established on-campus MCIT degree online. The MCIT
      Online program empowers students without computer science backgrounds to
      succeed in computing and technology fields. MCIT Online students come from
      diverse academic backgrounds ranging from business and history to
      chemistry and medicine. The online Master of Computer and Information
      Technology degree (MCIT Online) is an online masters degree in Computer
      Science tailored for non-Computer Science majors. Offered by the
      University of Pennsylvania, this new program brings the long-running,
      established on-campus MCIT degree online. The MCIT Online program empowers
      students without computer science backgrounds to succeed in computing and
      technology fields. MCIT Online students come from diverse academic
      backgrounds ranging from business and history to chemistry and medicine.
      The online Master of Computer and Information Technology degree (MCIT
      Online) is an online masters degree in Computer Science tailored for
      non-Computer Science majors. Offered by the University of Pennsylvania,
      this new program brings the long-running, established on-campus MCIT
      degree online. The MCIT Online program empowers students without computer
      science backgrounds to succeed in computing and technology fields. MCIT
      Online students come from diverse academic backgrounds ranging from
      business and history to chemistry and medicine. The online Master of
      Computer and Information Technology degree (MCIT Online) is an online
      masters degree in Computer Science tailored for non-Computer Science
      majors. Offered by the University of Pennsylvania, this new program brings
      the long-running, established on-campus MCIT degree online. The MCIT
      Online program empowers students without computer science backgrounds to
      succeed in computing and technology fields. MCIT Online students come from
      diverse academic backgrounds ranging from business and history to
      chemistry and medicine. The online Master of Computer and Information
      Technology degree (MCIT Online) is an online masters degree in Computer
      Science tailored for non-Computer Science majors. Offered by the
      University of Pennsylvania, this new program brings the long-running,
      established on-campus MCIT degree online. The MCIT Online program empowers
      students without computer science backgrounds to succeed in computing and
      technology fields. MCIT Online students come from diverse academic
      backgrounds ranging from business and history to chemistry and medicine.
      chemistry and medicine. The online Master of Computer and Information
      Technology degree (MCIT Online) is an online masters degree in Computer
      Science tailored for non-Computer Science majors. Offered by the
      University of Pennsylvania, this new program brings the long-running,
      established on-campus MCIT degree online. The MCIT Online program empowers
      students without computer science backgrounds to succeed in computing and
      technology fields. MCIT Online students come from diverse academic
      backgrounds ranging from business and history to chemistry and medicine.
      chemistry and medicine. The online Master of Computer and Information
      Technology degree (MCIT Online) is an online masters degree in Computer
      Science tailored for non-Computer Science majors. Offered by the
      University of Pennsylvania, this new program brings the long-running,
      established on-campus MCIT degree online. The MCIT Online program empowers
      students without computer science backgrounds to succeed in computing and
      technology fields. MCIT Online students come from diverse academic
      backgrounds ranging from business and history to chemistry and medicine.
      chemistry and medicine. The online Master of Computer and Information
      Technology degree (MCIT Online) is an online masters degree in Computer
      Science tailored for non-Computer Science majors. Offered by the
      University of Pennsylvania, this new program brings the long-running,
      established on-campus MCIT degree online. The MCIT Online program empowers
      students without computer science backgrounds to succeed in computing and
      technology fields. MCIT Online students come from diverse academic
      backgrounds ranging from business and history to chemistry and medicine.
      chemistry and medicine. The online Master of Computer and Information
      Technology degree (MCIT Online) is an online masters degree in Computer
      Science tailored for non-Computer Science majors. Offered by the
      University of Pennsylvania, this new program brings the long-running,
      established on-campus MCIT degree online. The MCIT Online program empowers
      students without computer science backgrounds to succeed in computing and
      technology fields. MCIT Online students come from diverse academic
      backgrounds ranging from business and history to chemistry and medicine.
      chemistry and medicine. The online Master of Computer and Information
      Technology degree (MCIT Online) is an online masters degree in Computer
      Science tailored for non-Computer Science majors. Offered by the
      University of Pennsylvania, this new program brings the long-running,
      established on-campus MCIT degree online. The MCIT Online program empowers
      students without computer science backgrounds to succeed in computing and
      technology fields. MCIT Online students come from diverse academic
      backgrounds ranging from business and history to chemistry and medicine.
    </div>
  );
};

About.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default About;
